modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="peacocking"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.peacocking]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.peacocking]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.peacocking]]
modId="curios"
mandatory=true
versionRange="{curios_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.peacocking]]
modId="octolib"
mandatory=true
versionRange="{octolib_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.peacocking]]
modId="relics"
mandatory=true
versionRange="{relics_version_range}"
ordering="NONE"
side="BOTH"
